### ISSUE TITLE
git/svn commands called with open4 hang on Snow Leopard

### ISSUE THREAD

**Issue by sminnee** [francois/piston#5]
A piston update command was hanging for me, on the waitpid2 calls in the svn/client and git/client.  I was able to fix this by replacing the open4 calls with the fallback backtick code.

I'm running Snow Leopard OSX.

Any idea why this might be?

**Comment by francois** [comment]
I've had that myself a few times. I didn't know what was the problem. Maybe I should fork + exec instead of using open4? I'd have to re-read the open4 library to know for sure. Could you submit a patch that removes open4 completely? Everything should still work, and it should be better for you.

Thanks for the investigation!
François
